language: cpp
sudo: required

before_install:
  - export GCC="$GCC -m64 -fPIC -DPIC" GXX="$GXX -m64 -fPIC -DPIC"
  - make -C crunch lib
  - sudo make -C crunch install-so
  - make -C crunch++ lib
  - sudo make -C crunch++ install-so
install:
  - make -C crunch crunch
  - make -C crunch++ crunch++
  - make -C crunchMake
  - sudo make install

script:
  - make -C crunch test
  - make -C crunch++ test
  - make -C crunch check
  - make -C crunch++ check

matrix:
  include:
    #- compiler: clang
    #  env: GCC=clang GXX=clang++
    - compiler: gcc-4.9
      env: GCC=gcc-4.9 GXX=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
    - compiler: gcc-5
      env: GCC=gcc-5 GXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
    - compiler: gcc-6
      env: GCC=gcc-6 GXX=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
