language: cpp
sudo: required
#dist: trusty

before_install:
  - export GCC="$CC -m64 -fPIC -DPIC" GXX="$CXX -m64 -fPIC -DPIC"
  - (cd crunch++ && make lib && sudo make install-so)
  - (cd crunch && make lib && sudo make install-so)
install:
  - make
  - sudo make install

script:
  - (cd crunch++ && make test && make check)

matrix:
  include:
    - compiler: clang
    - compiler: gcc-4.9
      env: CC=gcc-4.9 CXX=g++-4.9
      addons:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
    - compiler: gcc-5
      env: CC=gcc-5 CXX=g++-5
      addons:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
          - g++-5
    - compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
