language: cpp
os: linux
dist: xenial

install: .travis-ci/install.sh
before_script:
  - if [ "$ENGINE" == "make" ]; then
      export GCC="$CC -m64 -fPIC -DPIC" GXX="$CXX -m64 -fPIC -DPIC";
      export PREFIX=$HOME/.local PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig;
    fi
  - .travis-ci/beforeScript.sh
script: .travis-ci/script.sh

after_success:
  - if [ "$COVERAGE" == "1" ]; then
      bash <(curl -s https://codecov.io/bash) -x "$GCOV";
    fi
after_failure:
  - if [ "$ENGINE" == "meson" ]; then
      cat build/meson-logs/testlog.txt || true;
    fi

matrix:
  include:
    - compiler: clang-3.8
      env: CC=clang-3.8 CXX=clang++-3.8 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - clang-3.8
            - python3.6
    - compiler: clang-3.9
      env: CC=clang-3.9 CXX=clang++-3.9 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - clang-3.9
            - python3.6
    - compiler: clang-4.0
      env: CC=clang-4.0 CXX=clang++-4.0 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - llvm-4.0
            - clang-4.0
            - python3.6
    - compiler: clang-5.0
      env: CC=clang-5.0 CXX=clang++-5.0 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - llvm-5.0
            - clang-5.0
            - python3.6
    - compiler: clang-6.0
      env: CC=clang-6.0 CXX=clang++-6.0 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - llvm-6.0
            - clang-6.0
            - python3.6
    - compiler: clang-6.0
      env: CC=clang-6.0 CXX=clang++-6.0 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - llvm-6.0
            - clang-6.0
            - python3.6
    - compiler: clang-7
      env: CC=clang-7 CXX=clang++-7 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - llvm-7
            - clang-7
            - python3.6
    - compiler: clang-7
      env: CC=clang-7 CXX=clang++-7 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - llvm-7
            - clang-7
            - python3.6
    - compiler: clang-8
      env: CC=clang-8 CXX=clang++-8 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - llvm-8
            - clang-8
            - python3.6
    - compiler: clang-8.0
      env: CC=clang-8 CXX=clang++-8 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - llvm-8
            - clang-8
            - python3.6
    - compiler: gcc-4.9
      env: CC=gcc-4.9 CXX=g++-4.9 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc-4.9
            - g++-4.9
            - python3.6
    - compiler: gcc-5
      env: CC=gcc-5 CXX=g++-5 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc-5
            - g++-5
            - python3.6
    - compiler: gcc-6
      env: CC=gcc-6 CXX=g++-6 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc-6
            - g++-6
            - python3.6
    - compiler: gcc-7
      env: CC=gcc-7 CXX=g++-7 GCOV=gcov-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc-7
            - g++-7
            - python3.6
    - compiler: gcc-7
      env: CC=gcc-7 CXX=g++-7 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc-7
            - g++-7
            - python3.6
    - compiler: gcc-8
      env: CC=gcc-8 CXX=g++-8 GCOV=gcov-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc-8
            - g++-8
            - python3.6
    - compiler: gcc-8
      env: CC=gcc-8 CXX=g++-8 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc-8
            - g++-8
            - python3.6
    - compiler: gcc-9
      env: CC=gcc-9 CXX=g++-9 GCOV=gcov-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc-9
            - g++-9
            - python3.6
    - compiler: gcc-9
      env: CC=gcc-9 CXX=g++-9 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc-9
            - g++-9
            - python3.6
    - compiler: gcc-8
      env: CC=gcc-8 CXX=g++-8 COVERAGE=0 ENGINE=make
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
    - env: ARCH=amd64 COVERAGE=0 PATH=/c/tools/ninja-build:/c/Python37/Scripts:/c/Python37:$PATH
      os: windows
    - env: ARCH=x86 COVERAGE=0 PATH=/c/tools/ninja-build:/c/Python37/Scripts:/c/Python37:$PATH
      os: windows
#    - env: ARCH=amd64 COVERAGE=0 PATH="/c/tools/ninja-build:/c/Python37/Scripts:/c/Python37:/c/Program Files/LLVM/bin:$PATH" CC=clang CXX=clang++
#      os: windows

env:
  global:
    - COVERAGE=1
    - ENGINE=meson

notifications:
  email:
    on_success: change
    on_failure: change
