language: cpp
os: linux
dist: bionic

install: .travis-ci/install.sh
before_script: .travis-ci/beforeScript.sh
script: .travis-ci/script.sh

after_success:
  - if [ "$COVERAGE" == "1" ]; then
      bash <(curl -s https://codecov.io/bash) -x "$GCOV";
    fi
after_failure:
  - cat build/meson-logs/testlog.txt || true;

cache:
  pip: true
  directories:
    - /tmp/coverity-scan-analysis

matrix:
  include:
    - compiler: clang-5.0
      env: CC=clang-5.0 CXX=clang++-5.0 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-5.0
            - python3.7
      if: branch != coverityScan
    - compiler: clang-6.0
      env: CC=clang-6.0 CXX=clang++-6.0 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-6.0
            - python3.7
      if: branch != coverityScan
    - compiler: clang-7
      env: CC=clang-7 CXX=clang++-7 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-7
            - python3.7
      if: branch != coverityScan
    - compiler: clang-7
      env: CC=clang-7 CXX=clang++-7 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-7
            - python3.7
      if: branch != coverityScan
    - compiler: clang-8
      env: CC=clang-8 CXX=clang++-8 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-8
            - python3.7
      if: branch != coverityScan
    - compiler: clang-8
      env: CC=clang-8 CXX=clang++-8 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-8
            - python3.7
      if: branch != coverityScan
    - compiler: clang-9
      env: CC=clang-9 CXX=clang++-9 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-9
            - python3.7
      if: branch != coverityScan
    - compiler: clang-9
      env: CC=clang-9 CXX=clang++-9 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-9
            - python3.7
      if: branch != coverityScan
    - compiler: clang-10
      env: CC=clang-10 CXX=clang++-10 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-10
            - python3.7
      if: branch != coverityScan
    - compiler: clang-10
      env: CC=clang-10 CXX=clang++-10 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - deadsnakes
          packages:
            - g++-9
            - clang-10
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-5
      env: CC=gcc-5 CXX=g++-5 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-5
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-6
      env: CC=gcc-6 CXX=g++-6 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-6
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-7
      env: CC=gcc-7 CXX=g++-7 GCOV=gcov-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-7
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-7
      env: CC=gcc-7 CXX=g++-7 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-7
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-8
      env: CC=gcc-8 CXX=g++-8 GCOV=gcov-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-8
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-8
      env: CC=gcc-8 CXX=g++-8 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-8
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-9
      env: CC=gcc-9 CXX=g++-9 GCOV=gcov-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-9
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-9
      env: CC=gcc-9 CXX=g++-9 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-9
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-10
      env: CC=gcc-10 CXX=g++-10 GCOV=gcov-10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-10
            - python3.7
      if: branch != coverityScan
    - compiler: gcc-10
      env: CC=gcc-10 CXX=g++-10 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-10
            - python3.7
      if: branch != coverityScan
#    - env: ARCH=amd64 COVERAGE=0 PATH=/c/tools/ninja-build:/c/Python37/Scripts:/c/Python37:$PATH
#      os: windows
#      if: branch != coverityScan
#    - env: ARCH=x86 COVERAGE=0 PATH=/c/tools/ninja-build:/c/Python37/Scripts:/c/Python37:$PATH
#      os: windows
#      if: branch != coverityScan
#    - env: ARCH=amd64 COVERAGE=0 PATH="/c/tools/ninja-build:/c/Python37/Scripts:/c/Python37:/c/Program Files/LLVM/bin:$PATH" CC=clang CXX=clang++
#      os: windows
#      if: branch != coverityScan
    - compiler: gcc-9
      env:
        - CC=gcc-9 CXX=g++-9 COVERAGE=0 COVERITY_PROJECT_NAME=DX-MON/crunch
        - secure: "F5Sjj6am7EmjkgP3YGUe2WpLnC/UNnBXJ/aJpH3DDq1wFef7jhkNhGZvSrv6ls6AvR4WotkEU8sfEUfzs2H9W0c5rwySCEvK8u8AvTNxvHzQoBNh2BPpriVZlrHpkurFwQmzLjXomKuLy8q1dfQCwDnt+ZLrXRmxHCH0ziDgGSQ="
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-9
            - python3.7
      before_install:
        - . .travis-ci/installCoverity.sh
      before_script:
        - meson build --prefix=$HOME/.local
      script:
        - cov-build --dir cov-int ninja -C build
      after_script:
        - VERSION=`meson introspect build --projectinfo | jq -r '.["version"]'`-`git rev-parse --short HEAD`
        - tar cJf crunch.tar.xz cov-int
        - |
          curl --form token=${COVERITY_SCAN_TOKEN} \
            --form email=dx-mon@users.sourceforge.net \
            --form file=@crunch.tar.xz \
            --form version=$VERSION \
            --form description="crunch your code. Crunch is a unit testing framework written for C and C++." \
            https://scan.coverity.com/builds?project=DX-MON%2Fcrunch
      after_failure: cat cov-int/build-log.txt
      if: branch = coverityScan

env:
  global:
    - COVERAGE=1

notifications:
  email:
    on_success: change
    on_failure: change
