build:
  parallel: true
  project: VS/crunch.sln

image:
  - Visual Studio 2015
  - Visual Studio 2017

#platform:
#  - x86
#  - x64

install:
  - cmd: choco install ninja

configuration:
  - Debug
  - Release

environment:
  matrix:
    - COVERAGE: 0
    - COVERAGE: 1

matrix:
  exclude:
    - configuration: Release
      COVERAGE: 1
